// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "./Verifier.sol"; // generated by snarkjs

contract AccessControl {
    Verifier public verifier;

    constructor(address verifierAddr) {
        verifier = Verifier(verifierAddr);
    }

    function verifyAgeOver18(
        uint[2] calldata a,
        uint[2][2] calldata b,
        uint[2] calldata c,
        uint[1] calldata publicSignals   // currentYear only
    ) external view returns (bool) {
        return verifier.verifyProof(a, b, c, publicSignals);
    }
}
